services:
  php:
    build:
      context: .
      dockerfile: dockerfile 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
    links: 
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: exemplo
    ports:
      - "5432:5432"

#docker compose up -d /// docker compose stop /// docker compose down
# criar no postgre dois banco de dados, um chamado gerenciador e outro chamado trivia, quando entrar no navegador botar localhost/gerenciador_tarefas ou localhost/trivia.
```